### ISSUE TITLE
Error when creating a new tiket (from external user)

### ISSUE THREAD

**Issue by simonecogno** [polonel/trudesk#103]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
When I create a ticket on the http://localhost:8118/newissue I get the following error:

```
11/1 16:23:56 [10352] - info:     .                              .o8                     oooo
11/1 16:23:56 [10352] - info:   .o8                             "888                     `888
11/1 16:23:56 [10352] - info: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
11/1 16:23:56 [10352] - info:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
11/1 16:23:56 [10352] - info:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
11/1 16:23:56 [10352] - info:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
11/1 16:23:56 [10352] - info:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
11/1 16:23:56 [10352] - info: ==========================================================================
11/1 16:23:56 [10352] - info: trudesk v1.0.1 Copyright (C) 2014-2018 Chris Brame
11/1 16:23:56 [10352] - info:
11/1 16:23:56 [10352] - info: Running in: development
11/1 16:23:56 [10352] - info: Time: Thu Nov 01 2018 16:23:56 GMT+0100 (CET)
11/1 16:23:56 [10352] - info: Connected to MongoDB
11/1 16:23:56 [10352] - info: TruDesk is now listening on port: 8118
11/1 16:23:56 [10352] - info: SocketServer Running
11/1 16:23:56 [10352] - debug: Checking Default Settings...
11/1 16:23:56 [10352] - debug: Starting Runners...
11/1 16:23:56 [10352] - info: trudesk Ready
11/1 16:23:56 [10352] - debug: Number of Tasks: 0
11/1 16:23:56 [Child:Cache:10353] - debug: Pulled 0
11/1 16:23:56 [Child:Cache:10353] - debug: Cache Loaded
11/1 16:24:06 [10352] - debug: User successfully connected: simone
11/1 16:25:15 [10352] - debug: User disconnected: xxx - xxxx
11/1 16:25:27 [10352] - debug: User successfully connected: xx
11/1 16:25:32 [10352] - debug: User disconnected: xxx - xxxx
11/1 16:25:52 [10352] - debug:  message=tickets validation failed: priority: Cast to ObjectID failed for value "1" at path "priority", message=Cast to ObjectID failed for value "1" at path "priority", name=CastError, stringValue="1", kind=ObjectID, value=1, path=priority, message=Cast to ObjectId failed for value "1" at path "priority", name=CastError, stringValue="1", kind=ObjectId, value=1, path=priority, reason=undefined, _message=tickets validation failed, stack=ValidationError: tickets validation failed: priority: Cast to ObjectID failed for value "1" at path "priority"
    at new ValidationError (/Users/xxxx/WebstormProject/trudesk/node_modules/mongoose/lib/error/validation.js:27:11)
    at model.Document.invalidate (/Users/xxx/WebstormProject/trudesk/node_modules/mongoose/lib/document.js:1882:32)
    at model.$set (/Users/xxx/WebstormProject/trudesk/node_modules/mongoose/lib/document.js:878:10)
    at model._handleIndex (/Users/xxxx/WebstormProject/trudesk/node_modules/mongoose/lib/document.js:688:14)
    at model.$set (/Users/xx/WebstormProject/trudesk/node_modules/mongoose/lib/document.js:645:22)
    at model.Document (/Users/xxx/WebstormProject/trudesk/node_modules/mongoose/lib/document.js:112:12)
    at model.Model (/Users/xx/WebstormProject/trudesk/node_modules/mongoose/lib/model.js:67:12)
    at new model (/Users/xxx/WebstormProject/trudesk/node_modules/mongoose/lib/model.js:4300:13)
    at /Users/xxxx/WebstormProject/trudesk/src/controllers/api/v1/tickets.js:440:26
    at /Users/xxx/WebstormProject/trudesk/node_modules/mongoose/lib/model.js:4451:16
    at model.Query.(anonymous function).call (/Users/xxx/WebstormProject/trudesk/node_modules/mongoose/lib/query.js:3606:7)
    at /Users/xxx/WebstormProject/trudesk/node_modules/kareem/index.js:315:21
    at /Users/xxxx/WebstormProject/trudesk/node_modules/kareem/index.js:135:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9), name=ValidationError
```

Browser console error:
`Failed to load resource: the server responded with a status of 400 (Bad Request)
api/v1/public/tickets/create:1 `

**What did you expect to happen**:
A ticket from an external user should be created.

**How to reproduce it (as minimally and precisely as possible)**:
Just enter a ticket information on the  http://localhost:8118/newissue path.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: master
- OS (e.g. from /etc/os-release):MAC OS X 10-13
- Node.JS Version:8.10
- MongoDB Version:3.6.4
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
This is due to an incomplete version of the documentation. 

Please see https://github.com/polonel/trudesk/issues/98

It’s in the process of being updated as we speak.
