### ISSUE TITLE
Restart Me not working after web install

### ISSUE THREAD

**Issue by danleyb2** [polonel/trudesk#119]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ x] BUG 
- [ ] FEATURE

**What happened**:
Click **RESTART ME** at the end of the install steps doesn't work and throws the error bellow.  
If you don't restart after the install steps you'll keep getting redirect to /install 
```
12/8 18:51:40 [25625] - error:  message=process name not found, stack=Error: process name not found
    at /home/danleyb2/WebstormProjects/trudesk/node_modules/pm2/lib/API.js:1371:26
    at /home/danleyb2/WebstormProjects/trudesk/node_modules/pm2/lib/Client.js:707:12
    at /home/danleyb2/WebstormProjects/trudesk/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/home/danleyb2/WebstormProjects/trudesk/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:182:13)
    at Parser._write (/home/danleyb2/WebstormProjects/trudesk/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Parser.Writable.write (_stream_writable.js:294:11)
    at Socket.ondata (_stream_readable.js:666:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**What did you expect to happen**:
The server to be restarted

**How to reproduce it (as minimally and precisely as possible)**:
- Do a fresh clone of master
- run the setup steps in the README
- Run the install steps in the browser
- On the last step when you click **RESTART ME**, check console

**Anything else we need to know?**:
Manually doing `Ctrl + C` then `npm start` on the console does a restart

**Environment**:
- Trudesk Version: 1.0.3
- OS (e.g. from /etc/os-release): 18.04.1 LTS (Bionic Beaver)
- Node.JS Version: v10.13.0
- MongoDB Version: v3.6.3
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
The server can only restart itself if the process was running under `PM2`, or `runner.js` (docker). This isn't a bug rather than a limitation.
