### ISSUE TITLE
backup crash

### ISSUE THREAD

**Issue by earteza** [polonel/trudesk#126]
```
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'archiver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Administrator\Documents\radidesk\src\backup\backup.js:19:16)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

```
error on backup.js (edited) 
maybe missing dependency?

**Comment by polonel** [comment]
You have to run ‘yarn install’ to download the dependencies. You should do this after every upgrade.

**Comment by earteza** [comment]
alway do that, 

```
yarn install
yarn install v1.12.3
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
[5/6] Building fresh packages...
[6/6] Cleaning modules...
success Saved lockfile.
```

**Comment by earteza** [comment]
May be Something missing there , will check and update you

**Comment by polonel** [comment]
You can try to remove the node_modules folder and then run yarn install. Its definitely in the package.json at tag 1.0.5

https://github.com/polonel/trudesk/blob/v1.0.5/package.json#L24

**Comment by earteza** [comment]
Ok Thanks
