### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by tmswr** [polonel/trudesk#139]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:

Trudesk will not start after restarting from initial setup.

**What did you expect to happen**:

Trudesk to launch

**How to reproduce it (as minimally and precisely as possible)**:

Setup Trudesk and MongoDB as described, setup, and wait for reload.

**Anything else we need to know?**:

Log:
`
0|trudesk  | 1/28 13:02:18 [6000] - info:     .                              .o8                     oooo
0|trudesk  | 1/28 13:02:18 [6000] - info:   .o8                             "888                     `888
0|trudesk  | 1/28 13:02:18 [6000] - info: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
0|trudesk  | 1/28 13:02:18 [6000] - info:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
0|trudesk  | 1/28 13:02:18 [6000] - info:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
0|trudesk  | 1/28 13:02:18 [6000] - info:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
0|trudesk  | 1/28 13:02:18 [6000] - info:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
0|trudesk  | 1/28 13:02:18 [6000] - info: ==========================================================================
0|trudesk  | 1/28 13:02:18 [6000] - info: trudesk v1.0.5 Copyright (C) 2014-2019 Chris Brame
0|trudesk  | 1/28 13:02:18 [6000] - info:
0|trudesk  | 1/28 13:02:18 [6000] - info: Running in: development
0|trudesk  | 1/28 13:02:18 [6000] - info: Server Time: Mon Jan 28 2019 13:02:18 GMT-0600 (Central Standard Time)
0|trudesk  | 1/28 13:02:19 [6000] - info: Connected to MongoDB
0|trudesk  | 1/28 13:02:22 [6000] - info: TruDesk is now listening on port: 8118
0|trudesk  | 1/28 13:02:22 [6000] - info: SocketServer Running
0|trudesk  | 1/28 13:02:23 [6000] - debug: Checking Default Settings...
0|trudesk  | 1/28 13:02:23 [6000] - debug: Windows platform detected. Downloading MongoDB Tools
0|trudesk  | ReferenceError: internalBinding is not defined
0|trudesk  |     at internal/util/inspect.js:31:15
0|trudesk  |     at req_ (c:\trudesk\node_modules\natives\index.js:140:5)
0|trudesk  |     at require (c:\trudesk\node_modules\natives\index.js:113:12)
0|trudesk  |     at util.js:25:21
0|trudesk  |     at req_ (c:\trudesk\node_modules\natives\index.js:140:5)
0|trudesk  |     at require (c:\trudesk\node_modules\natives\index.js:113:12)
0|trudesk  |     at fs.js:42:21
0|trudesk  |     at req_ (c:\trudesk\node_modules\natives\index.js:140:5)
0|trudesk  |     at Object.req [as require] (c:\trudesk\node_modules\natives\index.js:54:10)
0|trudesk  |     at Object.<anonymous> (c:\trudesk\node_modules\unzip\node_modules\graceful-fs\fs.js:1:99)
0|trudesk  |     at Module._compile (internal/modules/cjs/loader.js:689:30)
0|trudesk  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
0|trudesk  |     at Module.load (internal/modules/cjs/loader.js:599:32)
0|trudesk  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
0|trudesk  |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
0|trudesk  |     at Module.require (internal/modules/cjs/loader.js:637:17)
0|trudesk  |     at require (internal/modules/cjs/helpers.js:22:18)
0|trudesk  |     at Object.<anonymous> (c:\trudesk\node_modules\unzip\node_modules\graceful-fs\graceful-fs.js:3:27)
0|trudesk  |     at Module._compile (internal/modules/cjs/loader.js:689:30)
0|trudesk  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
0|trudesk  |     at Module.load (internal/modules/cjs/loader.js:599:32)
0|trudesk  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
`

**Environment**:
- Trudesk Version: 1.0.5
- OS (e.g. from /etc/os-release): Windows 10
- Node.JS Version: 10.15.0
- MongoDB Version: 4.0.5
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Do you have the windows build tools installed?

Did it show an error when building the native modules with yarn install?

**Comment by tmswr** [comment]
I just uninstalled and reinstalled Windows Build Tools to check and see if that was the issue, I'm still not getting any connectivity. 

I did not get any errors while building modules either.

**Comment by polonel** [comment]
It has to do with an outdated dep. Working on a fix.
In the meantime you can comment out [these 3 lines](https://github.com/polonel/trudesk/blob/master/src/settings/defaults.js#L370-L372) and restart the server and it should work. 

NOTE: The backup system will not work on windows after commenting this out.

**Comment by tmswr** [comment]
Thank you for your superior support. I was overthinking this, glad to have it figured out!

**Comment by polonel** [comment]
This was fixed in `1.0.6`
