### ISSUE TITLE
[BUG] New User Registration broken on signup page

### ISSUE THREAD

**Issue by Pummelchen** [polonel/trudesk#167]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
After completing the new account signup page, TruDesk is stuck with this message: 

"## Creating Account...
Please wait while we create your account."

**What did you expect to happen**:
The account should be created and a conformation should show up, maybe a welcome Email send.

**How to reproduce it (as minimally and precisely as possible)**:
Use TruDesk 1.07 and MongoDB 4.0.6, once all runs fine try to create a new account using the Sign-Up link on the login page.

**Anything else we need to know?**:
It is possible to create an account manually in the account section. Mobile access also works once token is created. 

**Environment**:
- Trudesk Version: 1.07
- OS (e.g. from /etc/os-release): Windows 2019
- Node.JS Version: 11.11.0
- MongoDB Version: 4.0.6
- Is this hosted on cloud.trudesk.io: Nope, in VirtualBox

**Comment by Pummelchen** [comment]
Node.js console logs:

3/15 03:21:28 [380] - debug:  message=accounts validation failed: role: Cast to ObjectID failed for value "user" at path "role", message=Cast to ObjectID failed for value "user" at path "role", name=CastError, stringValue="user", kind=ObjectID, value=user, path=role, message=Cast to ObjectId failed for value "user" at path "role", name=CastError, stringValue="user", kind=ObjectId, value=user, path=role, reason=undefined, _message=accounts validation failed, stack=ValidationError: accounts validation failed: role: Cast to ObjectID failed for value "user" at path "role"
    at new ValidationError (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\mongoose\lib\error\validation.js:30:11)
    at model.Document.invalidate (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\mongoose\lib\document.js:2071:32)
    at model.$set (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\mongoose\lib\document.js:1021:10)
    at model._handleIndex (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\mongoose\lib\document.js:797:14)
    at model.$set (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\mongoose\lib\document.js:743:22)
    at model.Document (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\mongoose\lib\document.js:119:12)
    at model.Model (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\mongoose\lib\model.js:93:12)
    at new model (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\mongoose\lib\model.js:4503:13)
    at C:\Dropbox\Projects\TruDesk\trudesk\src\controllers\api\v1\users.js:272:16
    at nextTask (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\async\dist\async.js:5324:14)
    at Object.waterfall (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\async\dist\async.js:5334:5)
    at apiUsers.createPublicAccount (C:\Dropbox\Projects\TruDesk\trudesk\src\controllers\api\v1\users.js:268:9)
    at Layer.handle [as handle_request] (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\express\lib\router\route.js:137:13)
    at middleware.checkOrigin (C:\Dropbox\Projects\TruDesk\trudesk\src\middleware\middleware.js:167:10)
    at Layer.handle [as handle_request] (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\express\lib\router\route.js:137:13)
    at middleware.checkCaptcha (C:\Dropbox\Projects\TruDesk\trudesk\src\middleware\middleware.js:147:10)
    at Layer.handle [as handle_request] (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Dropbox\Projects\TruDesk\trudesk\node_modules\express\lib\router\layer.js:95:5), name=ValidationError
