### ISSUE TITLE
[BUG] New Issue creates an error 

### ISSUE THREAD

**Issue by Hardenberg** [polonel/trudesk#168]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:

i'll try to create an new Issue: 
http://localhost:8118/newissue
-> chrome: xxx:8118/api/v1/public/tickets/create 400 (Bad Request)
-> pm2: 

`3/15 11:22:16 [27243] - ^[[34mdebug^[[39m:  message=accounts validation failed: role: Cast to ObjectID failed for value "user" at path "role", message=Cast to ObjectID failed for value "user" at path "ro$
    at new ValidationError (/service/trudesk/node_modules/mongoose/lib/error/validation.js:30:11)              
    at model.Document.invalidate (/service/trudesk/node_modules/mongoose/lib/document.js:2071:32)             
    at model.$set (/service/trudesk/node_modules/mongoose/lib/document.js:1021:10)
    at model._handleIndex (/service/trudesk/node_modules/mongoose/lib/document.js:797:14)
    at model.$set (/service/trudesk/node_modules/mongoose/lib/document.js:743:22)
    at model.Document (/service/trudesk/node_modules/mongoose/lib/document.js:119:12)
    at model.Model (/service/trudesk/node_modules/mongoose/lib/model.js:93:12)                   
    at new model (/service/trudesk/node_modules/mongoose/lib/model.js:4503:13)
    at /service/trudesk/src/controllers/api/v1/tickets.js:442:16                         
    at nextTask (/service/trudesk/node_modules/async/dist/async.js:5324:14)            
    at Object.waterfall (/service/trudesk/node_modules/async/dist/async.js:5334:5)
    at apiTickets.createPublicTicket (/service/trudesk/src/controllers/api/v1/tickets.js:433:9)                 
    at Layer.handle [as handle_request] (/service/trudesk/node_modules/express/lib/router/layer.js:95:5)
    at next (/service/trudesk/node_modules/express/lib/router/route.js:137:13)
    at middleware.checkOrigin (/service/trudesk/src/middleware/middleware.js:167:10)
    at Layer.handle [as handle_request] (/service/trudesk/node_modules/express/lib/router/layer.js:95:5) 
    at next (/service/trudesk/node_modules/express/lib/router/route.js:137:13)
    at middleware.checkCaptcha (/service/trudesk/src/middleware/middleware.js:147:10)
    at Layer.handle [as handle_request] (/service/trudesk/node_modules/express/lib/router/layer.js:95:5)     
    at next (/service/trudesk/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/service/trudesk/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/service/trudesk/node_modules/express/lib/router/layer.js:95:5), name=ValidationError
`

**What did you expect to happen**:

A ticket from an external user should be created.

**How to reproduce it (as minimally and precisely as possible)**:

-> create an Issue as unknown user 

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.7
- OS (e.g. from /etc/os-release): debian 9
- Node.JS Version: 11.4 
- MongoDB Version: 4.0.6
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Ref #167

**Comment by polonel** [comment]
Fixed in v1.0.8
