### ISSUE TITLE
Hi After we have followed your steps we are getting the following error (with the stack trace):

### ISSUE THREAD

**Issue by sushant0219** [polonel/trudesk#216]
Hi After we have followed your steps we are getting the following error (with the stack trace):

6/10 16:19:04 [Child:Cache:13472] - debug: Pulled 413
6/10 16:19:05 [Child:Cache:13472] - warn:  message=Cast to ObjectId failed for value "admin" at path "_id" for model "roles", stack=CastError: Cast to ObjectId failed for value "admin" at path "_id" for model "roles"
    at new CastError (D:\trudesk\td\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (D:\trudesk\td\node_modules\mongoose\lib\schema\objectid.js:232:11)
    at ObjectId.SchemaType.applySetters (D:\trudesk\td\node_modules\mongoose\lib\schematype.js:845:12)
    at ObjectId.SchemaType._castForQuery (D:\trudesk\td\node_modules\mongoose\lib\schematype.js:1248:15)
    at ObjectId.SchemaType.castForQuery (D:\trudesk\td\node_modules\mongoose\lib\schematype.js:1238:15)
    at D:\trudesk\td\node_modules\mongoose\lib\schematype.js:1187:18
    at Array.map (<anonymous>)
    at ObjectId.handle$in (D:\trudesk\td\node_modules\mongoose\lib\schematype.js:1183:14)
    at ObjectId.SchemaType.castForQuery (D:\trudesk\td\node_modules\mongoose\lib\schematype.js:1235:20)
    at ObjectId.SchemaType.castForQueryWrapper (D:\trudesk\td\node_modules\mongoose\lib\schematype.js:1212:17)
    at cast (D:\trudesk\td\node_modules\mongoose\lib\cast.js:288:39)
    at model.Query.Query.cast (D:\trudesk\td\node_modules\mongoose\lib\query.js:4331:12)
    at model.Query.Query._castConditions (D:\trudesk\td\node_modules\mongoose\lib\query.js:1726:10)
    at model.Query.<anonymous> (D:\trudesk\td\node_modules\mongoose\lib\query.js:1753:8)
    at model.Query._wrappedThunk [as _find] (D:\trudesk\td\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)
    at D:\trudesk\td\node_modules\kareem\index.js:278:20, name=CastError, stringValue="admin", kind=ObjectId, value=admin, path=_id, reason=undefined, model=function model(doc, fields, skipId) {
      model.hooks.execPreSync('createModel', doc);
      if (!(this instanceof model)) {
        return new model(doc, fields, skipId);
      }
      Model.call(this, doc, fields, skipId);
    }
D:\trudesk\td\node_modules\mongoose\lib\utils.js:250
            throw error;
            ^

Error: Callback was already called.
    at D:\trudesk\td\node_modules\async\dist\async.js:966:32
    at D:\trudesk\td\node_modules\async\dist\async.js:3885:13
    at D:\trudesk\td\src\cache\quickStats.js:43:29
    at D:\trudesk\td\node_modules\mongoose\lib\model.js:4659:16
    at D:\trudesk\td\node_modules\mongoose\lib\utils.js:247:11
    at next (D:\trudesk\td\node_modules\mongoose\lib\model.js:3668:14)
    at next (D:\trudesk\td\node_modules\mongoose\lib\model.js:3828:21)
    at D:\trudesk\td\node_modules\mongoose\lib\model.js:4659:16
    at D:\trudesk\td\node_modules\mongoose\lib\utils.js:247:11
    at (anonymous function).call (D:\trudesk\td\node_modules\mongoose\lib\query.js:4057:18)
    at D:\trudesk\td\node_modules\kareem\index.js:246:48
    at D:\trudesk\td\node_modules\kareem\index.js:135:16
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at D:\trudesk\td\node_modules\mongoose\lib\model.js:4661:13
    at D:\trudesk\td\node_modules\mongoose\lib\utils.js:247:11
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:61:11)

_Originally posted by @sushant0219 in https://github.com/polonel/trudesk/issues/211#issuecomment-500384306_

**Comment by polonel** [comment]
You have no followed the upgrade steps provided on #211. V1.0.7 upgrades the permissions and those permissions have no been upgraded causing the role error. You must upgrade in the order provided.

Also do not creat a new issue from with the exact same problem and copy and paste the text from #211.
