### ISSUE TITLE
Unable to install trudesk on Amazon ec2 64bit ARM

### ISSUE THREAD

**Issue by shivajimagadum15** [polonel/trudesk#225]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ x] BUG

**What happened**:
Getting below error on yarn command:
```
yarn install v1.16.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
warning " > eslint-plugin-prettier@3.0.1" has unmet peer dependency "prettier@>= 1.13.0".
[5/6] Building fresh packages...
[1/6] ⢀ bcrypt
[-/6] ⢀ waiting...
[3/6] ⢀ dtrace-provider
[4/6] ⢀ node-sass
error /root/codebase/trudesk/node_modules/bcrypt: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /root/codebase/trudesk/node_modules/bcrypt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@12.4.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/root/codebase/trudesk/node_modules/bcrypt/lib/binding/bcrypt_lib.node" (not found)
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz
node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.6 and node@12.4.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.6/bcrypt_lib-v3.0.6-node-v72-linux-x64-glibc.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.4.0 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.4.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/root/codebase/trudesk/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/codebase/trudesk/node_modules/bcrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/codebase/trudesk/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/12.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/12.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/root/codebase/trudesk/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/12.4.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/codebase/trudesk/node_modules/bcrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.4.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/root/codebase/trudesk/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
make: g++: Command not found
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 127
make: Leaving directory `/root/codebase/trudesk/node_modules/bcrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/codebase/trudesk/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.14.114-105.126.amzn2.x86_64
gyp ERR! command "/root/.nvm/versions/node/v12.4.0/bin/node" "/root/codebase/trudesk/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/codebase/trudesk/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/root/codebase/trudesk/node_modules/bcrypt/lib/binding" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /root/codebase/trudesk/node_modules/bcrypt
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/root/.nvm/versions/node/v12.4.0/bin/node /root/codebase/trudesk/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/codebase/trudesk/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/root/codebase/trudesk/node_modules/bcrypt/lib/binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/codebase/trudesk/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 4.14.114-105.126.amzn2.x86_64
node-pre-gyp ERR! command "/root/.nvm/versions/node/v12.4.0/bin/node" "/root/codebase/trudesk/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /root/codebase/trudesk/node_modules/bcrypt
node-pre-gyp ERR! node -v v12.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
```

**What did you expect to happen**:
It should install properly
**How to reproduce it (as minimally and precisely as possible)**:
1) Git clone codebase from github
2) npm install -g yarn
3) yarn
getting above errror

**Environment**:
- Trudesk Version: v1.0.14
- OS (e.g. from /etc/os-release): Amazon ec2 ARM Linux kernel
- Node.JS Version: v12.4.0
- MongoDB Version: MongoDB atlas
- Is this hosted on cloud.trudesk.io: No

**Comment by akhlaaqbadulla** [comment]
@shivajimagadum15 i got these build errors with nodjs v12.4. but when i install v10 it seems to build just fine. i dont know why. 
cheers

**Comment by polonel** [comment]
@shivajimagadum15 Bcrypt doesn't have ARM binaries. You can try to run `npm rebuild bcrypt --build-from-source` I haven't built for ARM in a while but there is a tag on docker for ARM. `latest-arm` its a little behind. CircleCI builds on linux so I have to manually build ARM on my RP3.

https://cloud.docker.com/repository/docker/polonel/trudesk/tags

**Comment by shivajimagadum15** [comment]
@akhlaaqbadulla thanks, it works for me.
