### ISSUE TITLE
After installation, TruDesk never started.

### ISSUE THREAD

**Issue by mzch** [polonel/trudesk#273]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
After installation, TrueDesk never started.

**What did you expect to happen**:
Start successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
-- node runner
```
2019-10-31T09:09:29: PM2 log: Launching in no daemon mode
2019-10-31T09:09:29: PM2 log: App [trudesk:0] starting in -fork mode-
2019-10-31T09:09:29: PM2 log: App [trudesk:0] online
2019-10-31T09:09:32: PM2 log: App [trudesk:0] exited with code [1] via signal [SIGINT]
2019-10-31T09:09:32: PM2 log: App [trudesk:0] starting in -fork mode-
2019-10-31T09:09:32: PM2 log: App [trudesk:0] online
2019-10-31T09:09:35: PM2 log: App [trudesk:0] exited with code [1] via signal [SIGINT]
2019-10-31T09:09:35: PM2 log: App [trudesk:0] starting in -fork mode-
2019-10-31T09:09:35: PM2 log: App [trudesk:0] online
2019-10-31T09:09:38: PM2 log: App [trudesk:0] exited with code [1] via signal [SIGINT]
2019-10-31T09:09:38: PM2 log: App [trudesk:0] starting in -fork mode-
2019-10-31T09:09:38: PM2 log: App [trudesk:0] online
```
-- npm start
```
> trudesk@1.0.16 start /srv/trudesk/trudesk
> node ./app

10/31 09:19:36 [24719] - info:     .                              .o8                     oooo
10/31 09:19:36 [24719] - info:   .o8                             "888                     `888
10/31 09:19:36 [24719] - info: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
10/31 09:19:36 [24719] - info:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
10/31 09:19:36 [24719] - info:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
10/31 09:19:36 [24719] - info:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
10/31 09:19:36 [24719] - info:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
10/31 09:19:36 [24719] - info: ==========================================================================
10/31 09:19:36 [24719] - info: trudesk v1.0.16 Copyright (C) 2014-2019 Chris Brame
10/31 09:19:36 [24719] - info:
10/31 09:19:36 [24719] - info: Running in: development
10/31 09:19:36 [24719] - info: Server Time: Thu Oct 31 2019 09:19:36 GMT-0700 (Pacific Daylight Time)
10/31 09:19:37 [24719] - info: Connected to MongoDB
10/31 09:19:39 [24719] - debug: Checking Default Settings...
10/31 09:19:39 [24719] - debug: Timezone set to America/New_York
10/31 09:19:39 [24719] - warn: No Types Defined!
10/31 09:19:39 [24719] - debug: Registering Permissions...
10/31 09:19:39 [24719] - info: SocketServer Running
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Please upgrade to v1.0.7 Exiting...
    at /srv/trudesk/trudesk/src/migration/index.js:66:25
    at /srv/trudesk/trudesk/node_modules/mongoose/lib/model.js:4659:16
    at /srv/trudesk/trudesk/node_modules/mongoose/lib/utils.js:255:16
    at _hooks.execPost (/srv/trudesk/trudesk/node_modules/mongoose/lib/query.js:4065:11)
    at /srv/trudesk/trudesk/node_modules/kareem/index.js:135:16
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at /srv/trudesk/trudesk/node_modules/mongoose/lib/model.js:4661:13
    at /srv/trudesk/trudesk/node_modules/mongoose/lib/utils.js:255:16
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trudesk@1.0.16 start: `node ./app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the trudesk@1.0.16 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /srv/trudesk/.npm/_logs/2019-10-31T16_19_39_433Z-debug.log
```
**Environment**:
- Trudesk Version: 1.0.16
- OS (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- Node.JS Version: 10.17.0
- MongoDB Version: 4.2.1
- Is this hosted on cloud.trudesk.io: No, self-hosted

**Comment by mzch** [comment]
Well, I tried fresh reinstallation, then this issue has been fixed. Thanks.
