### ISSUE TITLE
Not Work install Ubuntu 64bits

### ISSUE THREAD

**Issue by tjaoc** [polonel/trudesk#280]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
/var/www/helpdesk/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (72)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports (/var/www/helpdesk/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/var/www/helpdesk/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/www/helpdesk/src/sass/buildsass.js:17:12)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.module.exports.installServer (/var/www/helpdesk/src/webserver.js:126:5)
    at launchInstallServer (/var/www/helpdesk/app.js:99:6)
    at Object.<anonymous> (/var/www/helpdesk/app.js:105:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: last
- OS (e.g. from /etc/os-release):
- Node.JS Version: 12
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
This is a node sass issue with your environment. Please check the node-sass documentation linked in the node-sass error message.
