### ISSUE TITLE
Messages Not Working

### ISSUE THREAD

**Issue by dregge8** [polonel/trudesk#36]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Starting a message does not open any type of window

**What did you expect to happen**:
Message popup

**How to reproduce it (as minimally and precisely as possible)**:
I am using Chrome v61, click on any user in the online panel.  Also clicking messages on the left hand side-panel does not seem to be showing anything besides the attempted conversations

server-side logs
```
11|trudesk | 11/9 11:32:44 [32201] - debug:  CastError: Cast to date failed for value "Invalid Date" at path "createdAt" for model "messages"
11|trudesk |     at new CastError (/home/trudesk/node_modules/mongoose/lib/error/cast.js:27:11)
11|trudesk |     at SchemaDate.cast (/home/trudesk/node_modules/mongoose/lib/schema/date.js:221:13)
11|trudesk |     at SchemaDate.handleSingle (/home/trudesk/node_modules/mongoose/lib/schema/date.js:256:15)
11|trudesk |     at SchemaDate.castForQuery (/home/trudesk/node_modules/mongoose/lib/schema/date.js:289:18)
11|trudesk |     at SchemaDate.SchemaType.castForQueryWrapper (/home/trudesk/node_modules/mongoose/lib/schematype.js:1035:17)
11|trudesk |     at cast (/home/trudesk/node_modules/mongoose/lib/cast.js:250:39)
11|trudesk |     at model.Query.Query.cast (/home/trudesk/node_modules/mongoose/lib/query.js:3204:12)
11|trudesk |     at model.Query.Query._castConditions (/home/trudesk/node_modules/mongoose/lib/query.js:1203:10)
11|trudesk |     at model.Query.Query._find (/home/trudesk/node_modules/mongoose/lib/query.js:1218:8)
11|trudesk |     at /home/trudesk/node_modules/kareem/index.js:250:8
11|trudesk |     at /home/trudesk/node_modules/kareem/index.js:23:7
11|trudesk |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
11|trudesk |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

chrome logs
```
Error: {&quot;message&quot;:&quot;Cast to date failed for value \&quot;Invalid Date\&quot; at path \&quot;createdAt\&quot; for model \&quot;messages\&quot;&quot;,&quot;name&quot;:&quot;CastError&quot;,&quot;stringValue&quot;:&quot;\&quot;Invalid Date\&quot;&quot;,&quot;kind&quot;:&quot;date&quot;,&quot;value&quot;:null,&quot;path&quot;:&quot;createdAt&quot;}
    at new CastError (/Users/xxx/bitbucket/trudesk/node_modules/mongoose/lib/error/cast.js:27:11)
    at SchemaDate.cast (/Users/xxx/bitbucket/trudesk/node_modules/mongoose/lib/schema/date.js:221:13)
    at SchemaDate.handleSingle (/Users/xxx/bitbucket/trudesk/node_modules/mongoose/lib/schema/date.js:256:15)
    at SchemaDate.castForQuery (/Users/xxx/bitbucket/trudesk/node_modules/mongoose/lib/schema/date.js:289:18)
    at SchemaDate.SchemaType.castForQueryWrapper (/Users/xxx/bitbucket/trudesk/node_modules/mongoose/lib/schematype.js:1035:17)
    at cast (/Users/xxx/bitbucket/trudesk/node_modules/mongoose/lib/cast.js:250:39)
    at model.Query.Query.cast (/Users/xxx/bitbucket/trudesk/node_modules/mongoose/lib/query.js:3204:12)
    at model.Query.Query._castConditions (/Users/xxx/bitbucket/trudesk/node_modules/mongoose/lib/query.js:1203:10)
    at model.Query.Query._find (/Users/xxx/bitbucket/trudesk/node_modules/mongoose/lib/query.js:1218:8)
    at /Users/xxx/bitbucket/trudesk/node_modules/kareem/index.js:250:8
    at /Users/xxx/bitbucket/trudesk/node_modules/kareem/index.js:23:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

```

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 0.1.10
- OS (e.g. from /etc/os-release): centos
- Node.JS Version: v8.8.0
- MongoDB Version: 2.6.12 - also attempted with v3.4.7 and had same error
- Is this hosted on cloud.trudesk.io:
no

**Comment by polonel** [comment]
When you attempted to try with MongoDB version 3.4 was it with a fresh database or the one created from 2.6?

**Comment by dregge8** [comment]
OK, I will try with mLab and see if it works.  Can you confirm what version of Node you are using? I wonder if that is my issue as well.

**Comment by dregge8** [comment]
update: I tried using different versions of node with fresh installs and still receive the error
v6.12.0
v8.8
v9.1

**Comment by polonel** [comment]
Thank you for all the information, it was very helpful. I have been able to reproduce the error and working on a fix. 

Stay tuned 👍

**Comment by dregge8** [comment]
Hey, thanks for the help!  I just reloaded and its working!
