### ISSUE TITLE
Mailer Check is not pulling mail/creating tickets using GMail…also can't seem to figure out where/how to turn on debug logging

### ISSUE THREAD

**Issue by ropelletier** [polonel/trudesk#432]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ X] BUG 
- [ ] FEATURE

**What happened**:
Setup gmail with known proper setting, including turning on allow less secure apps in gmail. Checked to create account if it does not exist.

Mail Server imap.gmail.com
Port 993

**What did you expect to happen**: Expected to create a ticket from email

**How to reproduce it (as minimally and precisely as possible)**:
Clicking Check Now

**Anything else we need to know?**:
The log shows nothing useful at all?? Where am I supposed to find the logs for troubleshooting this? Do I need to turn on debugging somehow?

```
                                8/20 11:06:28 [25] - info:     .                              .o8                     oooo
8/20 11:06:28 [25] - info:   .o8                             "888                     `888
8/20 11:06:28 [25] - info: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
8/20 11:06:28 [25] - info:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
8/20 11:06:28 [25] - info:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
8/20 11:06:28 [25] - info:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
8/20 11:06:28 [25] - info:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
8/20 11:06:28 [25] - info: ==========================================================================
8/20 11:06:28 [25] - info: trudesk v1.1.8-ai16 Copyright (C) 2014-2021 Chris Brame
8/20 11:06:28 [25] - info:  
8/20 11:06:28 [25] - info: Running in: production
8/20 11:06:28 [25] - info: Server Time: Fri Aug 20 2021 11:06:28 GMT+0000 (Coordinated Universal Time)
8/20 11:06:28 [25] - info: Connected to MongoDB
8/20 11:06:30 [25] - info: SocketServer Running
8/20 11:06:30 [25] - info: TruDesk is now listening on port: 8118
8/20 11:06:30 [25] - info: trudesk Ready
                            Invalid Log File...
```

**Environment**:
- Trudesk Version: Trudesk version 1.1.8
- OS (e.g. from /etc/os-release): Ubuntu 20.04.2 LTS
- I am using the Docker image

**Comment by ropelletier** [comment]
I changed NODE_ENV to development and I thing I am now seeing the correct logs.

```
8/20 11:37:46 [25] - debug:  message=Cannot call write after a stream was destroyed, stack=Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at clearBuffer (_stream_writable.js:542:7)
    at Socket.Writable.uncork (_stream_writable.js:338:7)
    at JSStreamSocket.doWrite (internal/js_stream_socket.js:176:17)
    at JSStream.onwrite (internal/js_stream_socket.js:33:57)
    at Socket.ondata (internal/js_stream_socket.js:77:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23), code=ERR_STREAM_DESTROYED, source=socket
8/20 11:37:46 [25] - debug:  message=self signed certificate, stack=Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12)
    at Socket.ondata (internal/js_stream_socket.js:77:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23), code=DEPTH_ZERO_SELF_SIGNED_CERT, source=socketInvalid Log File...
```

**Comment by polonel** [comment]
Are you positive you are using Gmail? It is detecting a self-sign certificate and I'm sure Google doesn't use those.

**Comment by ropelletier** [comment]
Yes, I am absolutely using gmail. Though I also tested this against a Zimbra server and I am getting the same thing. I even set this up at different locations, including from my home server and I am still getting the same thing using the Docker image.

Has the latest Docker image been fully tested?

**Comment by ropelletier** [comment]
Can we reopen this? I apologize but I work in a K-12 school and as you can imagine the last couple of weeks in August are extremely busy and I just have not been able to circle back to this until now.

**Comment by polonel** [comment]
Yes, the docker container is used in production at multiple sites. I'm not sure what your setup looks like but the mailer is detecting a self-signed SSL cert and it's failing to connect. 

Trudesk doesn't provide any SSL certs so I'm not sure where it's detecting a self-sign cert in your infrastructure. 
I use Gmail, Zoho, Hotmail, Office 365 all in production with no issues on v1.1.8
