### ISSUE TITLE
After logging out or refreshing the window server is rebooting.

### ISSUE THREAD

**Issue by ellipe** [polonel/trudesk#48]
**Is this a BUG REPORT or FEATURE REQUEST?**:
- [ X] BUG 

**What happened**:
```
After logging out the server restarted.
TypeError: ansi_up.ansi_to_html is not a function
    at EventEmitter.<anonymous> (/Users/adm/Desktop/work/trudesk/src/socketserver.js:589:67)
    at EventEmitter.emit (events.js:160:13)
    at ReadStream.<anonymous> (/Users/adm/Desktop/work/trudesk/node_modules/file-tail/index.js:52:19)
    at ReadStream.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:252:13)
    at ReadStream.Readable.push (_stream_readable.js:213:10)
    at fs.read (fs.js:2117:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:676:17)
```

**Environment**:
- Trudesk Version: TruDesk v0.1.10 Running in: development
- OS (e.g. from /etc/os-release): Ubuntu Server 16
- Node.JS Version: v9.5.0
- MongoDB Version: 3.4.13
- Is this hosted on cloud.trudesk.io: No

**Comment by ellipe** [comment]
Fix it like this, 
Added the 
            var AnsiUp = require('ansi_up');
            var ansi_up = new AnsiUp.default;
Now it's working properly.

```
socket.on('logs:fetch', function() {
            var path = require('path');
            var AnsiUp = require('ansi_up');
            var ansi_up = new AnsiUp.default;
            var fileTailer = require('file-tail');
            var fs = require('fs');
            var logFile = path.join(__dirname, '../logs/output.log');
            if (!fs.existsSync(logFile))
                utils.sendToSelf(socket, 'logs:data', 'Invalid Log File...');
            else {
                var ft = fileTailer.startTailing(logFile);
                ft.on('line', function(line) {
                    utils.sendToSelf(socket, 'logs:data', ansi_up.ansi_to_html(line));
                });
            }
        });
```

**Comment by polonel** [comment]
Thanks. I actually just fixed this last night. I overlooked it in the logs:fetch function when upgrading the ansi_up package. I'll get it pushed to developed tonight.
