### ISSUE TITLE
Cannot complete install - password contains an illegal unescaped character

### ISSUE THREAD

**Issue by jkornblum** [polonel/trudesk#50]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Could not complete install, gave error with no message.
`error.log` shows
```
{"level":"error","message":"Oh no, something went wrong with DB! - Password contains an illegal unescaped character","timestamp":"2018-02-21T03:23:20.368Z"}
```

`output.log` shows

```
2/20 21:21:12 [24555] - [32minfo[39m: Trudesk Install Server Running...
2/20 21:23:20 [24555] - [31merror[39m: Oh no, something went wrong with DB! - Password contains an illegal unescaped character
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Password contains an illegal unescaped character
    at parseConnectionString (/etc/trudesk/node_modules/mongodb/lib/url_parser.js:280:13)
    at parseHandler (/etc/trudesk/node_modules/mongodb/lib/url_parser.js:112:14)
    at module.exports (/etc/trudesk/node_modules/mongodb/lib/url_parser.js:19:12)
    at Promise (/etc/trudesk/node_modules/mongoose/lib/connection.js:330:5)
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (/etc/trudesk/node_modules/mongoose/lib/connection.js:329:17)
    at Mongoose.connect (/etc/trudesk/node_modules/mongoose/lib/index.js:206:15)
    at Object.module.exports.init (/etc/trudesk/src/database/index.js:45:18)
    at async.waterfall.counters._id (/etc/trudesk/src/controllers/install.js:152:16)
    at nextTask (/etc/trudesk/node_modules/async/dist/async.js:5310:14)
    at Object.waterfall (/etc/trudesk/node_modules/async/dist/async.js:5320:5)
    at installController.install (/etc/trudesk/src/controllers/install.js:150:11)
    at Layer.handle [as handle_request] (/etc/trudesk/node_modules/express/lib/router/layer.js:95:5)
    at next (/etc/trudesk/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/etc/trudesk/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/etc/trudesk/node_modules/express/lib/router/layer.js:95:5)
    at /etc/trudesk/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/etc/trudesk/node_modules/express/lib/router/index.js:335:12)
    at next (/etc/trudesk/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/etc/trudesk/node_modules/express/lib/router/index.js:174:3)
    at router (/etc/trudesk/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/etc/trudesk/node_modules/express/lib/router/layer.js:95:5)
```

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
use the install.sh on clean ubuntu 17.10 directory and attempt to install

**Anything else we need to know?**:
I got the screen where you create an admin account. I used password `817681`. I'm not sure if it is my password (doubt it) or the default mongo user `trudesk` which had special characters.

I changed both the mongo user password and my admin password to `password` and it let me complete installation.

**Environment**:
- Trudesk Version: (install.sh from 2/20)
- OS (e.g. from /etc/os-release):  Ubuntu 17.10
- Node.JS Version: 9.5
- MongoDB Version: 3.2.x
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Thank you for pointing this out. I see I overlooked one connection URI when I was updating packages.
