### ISSUE TITLE
What could be the problem

### ISSUE THREAD

**Issue by YaponchikLIN** [polonel/trudesk#541]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [Error: command or literal size is too large ] BUG 

**What happened**:
The site becomes unavailable and there is an error in the log

Error: command or literal size is too large
    at Connection._resTagged (/usr/src/trudesk/node_modules/imap/lib/Connection.js:1502:11)
    at Parser.<anonymous> (/usr/src/trudesk/node_modules/imap/lib/Connection.js:194:10)
    at Parser.emit (node:events:526:28)
    at Parser._resTagged (/usr/src/trudesk/node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (/usr/src/trudesk/node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (/usr/src/trudesk/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/usr/src/trudesk/node_modules/imap/lib/Parser.js:53:12)
    at TLSSocket.emit (node:events:526:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'no',
  textCode: undefined,
  source: 'protocol'
}

**What did you expect to happen**:
Create a user via Mailer
**How to reproduce it (as minimally and precisely as possible)**:
I specified the data for mailer check and clicked apply and check now

**Anything else we need to know?**:
Deployed everything using docker compose

**Comment by polonel** [comment]
This is an IMAP library error, meaning the email it is trying to parse is too big. Trudesk uses the IMAP js library to parse inbox emails. Without more information, it is hard to determine the exact email and its size.

**Comment by YaponchikLIN** [comment]
Thanks, that was the problem. I had to create a new mail to get rid of the error. I sent the same messages
