### ISSUE TITLE
Trudesk Crashing when creating ticket

### ISSUE THREAD

**Issue by sfulham** [polonel/trudesk#557]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Trudesk crashed when creating a ticket, when reconnected, the ticket is there.
If I try to access Trudesk while it is starting up again, I just get a Bad Gateway from traefik.

**What did you expect to happen**:
No disconnecting/crashing.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup trudesk with docker-compose and traefik
2. Change mongodb version to 4.4.6 (I had to do this as I had a warning that mongodb wont work due to not having avx support in my VM)

**Anything else we need to know?**:
No

**Environment**:
- Trudesk Version: 1 (0822f1a59e5e) (docker)
- OS (e.g. from /etc/os-release): AlmaLinux 8
- Node.JS Version: Docker
- MongoDB Version: 4.4.6
- Is this hosted on cloud.trudesk.io: No

**Comment by mrt-prodz** [comment]
Are you sure this is not `Traefik` related ? Can you get the same behavior doing something else or is it just after creating a ticket ? (creating a user / group..)

Anything in the logs ?

I run Trudesk in a docker with MongoDB 5.0 (mongo:5.0-focal) using Caddy as a reverse-proxy and I have not experienced any crash.

**Comment by polonel** [comment]
I have not tested trudesk with `MongoDB 4.4.6`
Are any errors shown in the logs? Usually, it will print out the crash dump when it crashes.

**Comment by sfulham** [comment]
I cannot find any unusual logs, other than Elasticsearch complaining, but I have not set that up in TruDesk yet anyway.

**Comment by polonel** [comment]
Need more information. I am not seeing any crashes when creating tickets. I've tested extensively to try and make it fail.

**Comment by e0xify** [comment]
same issue here,

`02-14-2023 17:37:10 [53] info:      .                              .o8                     oooo
02-14-2023 17:37:10 [53] info:    .o8                             "888                     `888
02-14-2023 17:37:10 [53] info:  .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
02-14-2023 17:37:10 [53] info:    888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
02-14-2023 17:37:10 [53] info:    888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
02-14-2023 17:37:10 [53] info:    888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
02-14-2023 17:37:10 [53] info:    "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
02-14-2023 17:37:10 [53] info:  ==========================================================================
02-14-2023 17:37:10 [53] info:  trudesk v1.2.6 Copyright (C) 2014-2022 Chris Brame
02-14-2023 17:37:10 [53] info: 
02-14-2023 17:37:10 [53] info:  Running in: production
02-14-2023 17:37:10 [53] info:  Server Time: Tue Feb 14 2023 17:37:10 GMT+0000 (Coordinated Universal Time)
02-14-2023 17:37:10 [53] info:  Connected to MongoDB
02-14-2023 17:37:13 [53] info:  SocketServer Running
02-14-2023 17:37:14 [53] info:  Trudesk is now listening on port: 8118
02-14-2023 17:37:14 [53] info:  trudesk Ready
02-14-2023 22:15:13 [53] error:         read ECONNRESET - Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
02-15-2023 02:10:13 [53] error:         read ECONNRESET - Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
02-15-2023 11:59:14 [53] error:         read ECONNRESET - Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
02-15-2023 16:19:14 [53] error:         read ECONNRESET - Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
02-15-2023 19:06:14 [53] error:         read ECONNRESET - Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
02-16-2023 04:26:14 [53] error:         read ECONNRESET - Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
02-16-2023 06:02:14 [53] error:         read ECONNRESET - Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
02-16-2023 06:31:14 [53] error:         read ECONNRESET - Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Error: No recipients defined
    at SMTPConnection._formatError (/usr/src/trudesk/node_modules/nodemailer/lib/smtp-connection/index.js:787:19)
    at SMTPConnection._setEnvelope (/usr/src/trudesk/node_modules/nodemailer/lib/smtp-connection/index.js:1004:34)
    at SMTPConnection.send (/usr/src/trudesk/node_modules/nodemailer/lib/smtp-connection/index.js:618:14)
    at sendMessage (/usr/src/trudesk/node_modules/nodemailer/lib/smtp-transport/index.js:228:28)
    at /usr/src/trudesk/node_modules/nodemailer/lib/smtp-transport/index.js:286:25
    at SMTPConnection._actionAUTHComplete (/usr/src/trudesk/node_modules/nodemailer/lib/smtp-connection/index.js:1553:9)
    at SMTPConnection.<anonymous> (/usr/src/trudesk/node_modules/nodemailer/lib/smtp-connection/index.js:543:26)
    at SMTPConnection._processResponse (/usr/src/trudesk/node_modules/nodemailer/lib/smtp-connection/index.js:950:20)
    at SMTPConnection._onData (/usr/src/trudesk/node_modules/nodemailer/lib/smtp-connection/index.js:752:14)
    at TLSSocket.SMTPConnection._onSocketData (/usr/src/trudesk/node_modules/nodemailer/lib/smtp-connection/index.js:191:44)
    at TLSSocket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'EENVELOPE',
  command: 'API'
}`

**Comment by e0xify** [comment]
@polonel reopen for logs
