### ISSUE TITLE
Mailer Check error

### ISSUE THREAD

**Issue by rmsferreira** [polonel/trudesk#79]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ x] BUG 
- [ ] FEATURE

I configure the mailer check on system but one error is diplay:

  warn: Failed to Create ticket from Email: ValidationError: issue: Path `issue` is required.
7/12 23:25:09 [1102] - warn:  ValidationError: tickets validation failed: issue: Path `issue` is required.
    at new ValidationError (/etc/trudesk/node_modules/mongoose/lib/error/validation.js:27:11)
    at model.Document.invalidate (/etc/trudesk/node_modules/mongoose/lib/document.js:1700:32)
    at /etc/trudesk/node_modules/mongoose/lib/document.js:1572:17
    at /etc/trudesk/node_modules/mongoose/lib/schematype.js:785:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: Trudesk version 1.0.0 
- OS (e.g. from /etc/os-release): Ubuntu 16.04
installed from ubunut scrip
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
@rmsferreira Thank you for your bug report. This error indicates that the message is failing to detect a `body` in the email message. (the email does not contain a text body)

Please make sure the email message has a body that contains text. 

Also if you could forward the email to polonel@trudesk.io it would be helpful in running the same message through to see exactly the fail case.
