### ISSUE TITLE
Crash in MailCheck

### ISSUE THREAD

**Issue by polonel** [polonel/trudesk#9]
Server crash when trying to convert mail -> ticket in mailcheck.js    

```
TypeError: Cannot read property '_id' of null
at /etc/trudesk/src/mailer/mailCheck.js:138:77
at Query. (/etc/trudesk/node_modules/mongoose/lib/query.js:2181:28)
at /etc/trudesk/node_modules/kareem/index.js:259:21
at /etc/trudesk/node_modules/kareem/index.js:127:16
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickDomainCallback (internal/process/next_tick.js:122:9)
---------------------------------------------
at Kareem.execPost (/etc/trudesk/node_modules/kareem/index.js:126:20)
at /etc/trudesk/node_modules/kareem/index.js:251:15
at Immediate. (/etc/trudesk/node_modules/mongoose/lib/query.js:1160:14)
at Immediate. (/etc/trudesk/node_modules/mquery/lib/utils.js:137:16)
at runCallback (timers.js:570:20)
at tryOnImmediate (timers.js:550:5)
at processImmediate [as _immediateCallback] (timers.js:529:5)
```

**Comment by polonel** [comment]
Default ticket type through MailCheck needs to be set through settings configuration. Currently the bug resides in a hard coded name of *Issue* as the ticket type. If That ticket type (name=issue) doesn't exist the server will crash.
